name: Deploy Google Cloud Functions

on:
  push:
    branches: [ main ]   
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions
      - name: Build
        run: npm run build
        working-directory: ./functions
      - name: Deploy to Firebase
        if: ${{ github.event_name != 'pull_request' }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
